Serafina/execution reduction
Mye-InfoBank/SIMBA-QC pull request #2
Opened 2024-04-29 09:15 UTC by serareif

2024-04-29 09:21 UTC, nictru requested changes

2024-04-29 09:21 UTC, nictru commented on src/sliders.py
> +        button()
`ui.output_ui("button")`

2024-04-29 09:21 UTC, nictru commented on src/sliders.py
> +    @render.ui
Add `@output` decorator

2024-04-29 12:16 UTC, serareif commented on src/sliders.py
> +        button()
done

2024-04-29 12:17 UTC, serareif commented on src/sliders.py
> +    @render.ui
done

2024-05-03 07:20 UTC, nictru requested changes
This PR is hard to review since basically everything changed. When looking at the files with `cat app.py -v`, one can see that there are Windows line endings everywhere (indicated by `^M`). You can remove these line using [dos2unix](https://linux.die.net/man/1/dos2unix).

2024-05-03 10:49 UTC, nictru commented
I think the way it is implemented now would still block the UI during execution. Check out the explanation [here](https://shiny.posit.co/py/docs/nonblocking.html#true-non-blocking-behavior-with-extendedtask) and make use of the `reactive.extended_task` decorator

2024-05-10 10:20 UTC, nictru approved these changes

2024-05-11 08:34 UTC, merged