Sera/float issue
Mye-InfoBank/SIMBA-QC pull request #6
Opened 2024-06-19 07:45 UTC by serareif

2024-06-19 09:23 UTC, nictru commented
The proposed solution is a symptomatic solution rather than a root-cause solution. I understand the problem only occurs in some AnnData objects; otherwise, we would have noticed it during earlier testing. This means that the structural differences should be solvable by converting the datatypes already when reading the input.

I understand that the monkey-patching looks rather elegant, but since `json.dumps` is a core functionality in networking, there might be negative side effects that we are unaware of - potentially just shifting the problem from one location to the other. Thus, I would not be comfortable merging this solution.

2024-06-19 09:23 UTC, nictru requested changes
The proposed solution is a symptomatic solution rather than a root-cause solution. I understand the problem only occurs in some AnnData objects; otherwise, we would have noticed it during earlier testing. This means that the structural differences should be solvable by converting the datatypes already when reading the input.

I understand that the monkey-patching looks rather elegant, but since json.dumps is a core functionality in networking, there might be negative side effects that we are unaware of - potentially just shifting the problem from one location to the other. Thus, I would not be comfortable merging this solution.

2024-06-19 10:18 UTC, serareif commented
"I understand the problem only occurs in some AnnData objects; otherwise, we would have noticed it during earlier testing"
The problem occurs in all of the AnnData object which we used before for testing too. It also occurs in the commits beforehand for the same AnnData objects, which worked well before. 
I will try to fix the issue by converting the datatypes beforehand.

2024-06-20 05:55 UTC, nictru approved these changes

2024-06-20 05:58 UTC, merged